### ISSUE TITLE
Additional URL shortening: smarturl.it

### ISSUE THREAD

**Issue by neoloc** [smfreegard/DecodeShortURLs#3]
Found a URL shortening service in spam that is not in your list.

Example:
http://smarturl.it/reportclosing

URL will take you to:
http://high-rollerz.com/snx/login.php?cmd=login_submit&id=f4a671bda2e4826e77450cd070ef8972f4a671bda2e4826e77450cd070ef8972&session=f4a671bda2e4826e77450cd070ef8972f4a671bda2e4826e77450cd070ef8972

**Comment by cepheid666** [comment]
This one has been on the list for a while, so this issue can be closed.  (I'd close it but I'm not a maintainer!)
